TEST_SIZE = 0.3
SEED = 1
BATCH_SIZE = 32
SPLIT_MINIMUM_COUNT = 10
columns=["Speed limit (5km/h)",
"Speed limit (15km/h)",
"Speed limit (30km/h)",
"Speed limit (40km/h)",
"Speed limit (50km/h)",
"Speed limit (60km/h)",
"Speed limit (70km/h)",
"speed limit (80km/h)",
"Dont Go straight or left",
"Dont Go straight or Right",
"Dont Go straight",
"Dont Go Left",
"Dont Go Left or Right",
"Dont Go Right",
"Dont overtake from Left",
"No Uturn",
"No Car",
"No horn",
"Speed limit (40km/h)",
"Speed limit (50km/h)",
"Go straight or right",
"Go straight",
"Go Left",
"Go Left or right"
"Go Right",
"keep Left",
"keep Right",
"Roundabout mandatory",
"watch out for cars",
"Horn",
"Bicycles crossing",
"Uturn",
"Road Divider",
"Traffic signals",
"Danger Ahead",
"Zebra Crossing",
"Bicycles crossing",
"Children crossing",
"Dangerous curve to the left",
"Dangerous curve to the right",
"Unknown1",
"Unknown2",
"Unknown3",
"Go right or straight",
"Go left or straight",
"Unknown4",
"ZigZag Curve",
"Train Crossing",
"Under Construction",
"Unknown5",
"Fences",
"Heavy Vehicle Accidents",
"Unknown6",
"Give Way",
"No stopping",
"No entry",
"Unknown7",
"Unknown8"
]
